# Use the official MySQL image as the base image
FROM mysql:5.6

# Set environment variables
ENV MYSQL_DATABASE="test_rbh"
ENV MYSQL_ROOT_PASSWORD="my-secret-pw"

# When the container starts, this SQL script will run
COPY ./resource/sql/1.sql /docker-entrypoint-initdb.d/

# Expose the port the database listens on
EXPOSE 3306
